"""Write FIGURE_LIST.md: the figure inventory with its specification check.

Reads the rendered PNGs rather than the plotting code, so what is recorded is what would be
submitted. The type-size floor cannot be read back from a raster, so it is enforced at draw
time by `figstyle.check()` and recorded here as the assertion that ran.
"""
import os
import re
from PIL import Image

FIGDIR = "aef_explore/paper/figures"
OUT = "aef_explore/paper/FIGURE_LIST.md"
MS = "aef_explore/paper/MANUSCRIPT.md"

FIGS = [
    ("F1_study_area.png", "Fig. 1", "study area", "fig_study_area.py"),
    ("F2_registration_curve.png", "Fig. 2", "registration curve", "fig_results.py f1"),
    ("F3_sar_stratification.png", "Fig. 3", "SAR stratification", "fig_results.py f2"),
    ("F4_deferral.png", "Fig. 4", "deferral", "fig_results.py f3"),
    ("F5_optically_late.png", "Fig. 5", "optically late events", "fig_results.py f4"),
    ("F6_reference_selection.png", "Fig. 6", "reference selection", "fig_results.py f5"),
    ("F7_offset_examples.png", "Fig. 7", "polygon-offset examples", "fig_offset.py"),
    ("F8_observation_supply.png", "Fig. 8", "observation supply", "fig_results.py f7"),
    ("F9_deferral_risk.png", "Fig. 9", "deferral risk", "fig_results.py f8"),
    ("M1_ParaBR163.png", "Fig. M1", "map plate, Pará / BR-163", "fig_maps.py"),
    ("M2_Roraima_S.png", "Fig. M2", "map plate, Roraima", "fig_maps.py"),
]


def first_sentence(label):
    """Pull the opening sentence of the figure's caption out of the manuscript."""
    txt = open(MS).read()
    pat = r"\*\*" + re.escape(label.replace("Fig. ", "Fig. ")) + r"\.?\*\*\s*(.+?)(?:\.\s|\.\n)"
    m = re.search(pat, txt, re.S)
    if not m:
        m = re.search(r"\*\*Fig\. M1, M2\.\*\*\s*(.+?)(?:\.\s|\.\n)", txt, re.S)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else "—"


def main():
    rows, problems = [], []
    for fname, label, short, script in FIGS:
        path = os.path.join(FIGDIR, fname)
        im = Image.open(path)
        dpi = im.info.get("dpi", (None, None))[0]
        w_mm = im.size[0] / dpi * 25.4 if dpi else float("nan")
        col = "double" if abs(w_mm - 190) < 1.0 else ("single" if abs(w_mm - 90) < 1.0 else "?")
        if col == "?" or round(dpi or 0) != 300:
            problems.append(f"{fname}: {w_mm:.1f} mm at {dpi} dpi")
        rows.append((label, short, fname, im.size, round(dpi or 0), w_mm, col, script,
                     os.path.getsize(path)))
    lines = [
        "# Figure list", "",
        "Generated by `code/figure_list.py` from the rendered files, so it records what would "
        "be submitted rather than what the plotting code intends. Every figure is drawn at "
        "final size: the width is the printed width and the type sizes are the printed type "
        "sizes.", "",
        "**Specification.** 300 dpi; 90 mm single column or 190 mm double column; no type "
        "below 7 pt. The first two are checked here against the files; the type floor is "
        "asserted at draw time by `figstyle.check()`, which refuses to save a figure "
        "containing any smaller text, so no figure in this list can violate it.", "",
        "| figure | subject | file | pixels | dpi | width | column | drawn by |",
        "|---|---|---|---|---|---|---|---|"]
    for label, short, fname, size, dpi, w_mm, col, script, nbytes in rows:
        lines.append(f"| **{label}** | {short} | `{fname}` | {size[0]} × {size[1]} | {dpi} | "
                     f"{w_mm:.0f} mm | {col} | `{script}` |")
    lines += ["", f"All {len(rows)} figures pass." if not problems else
              "**Failures:** " + "; ".join(problems), "",
              "## Captions, opening sentence", "",
              "The full captions are in `MANUSCRIPT.md`.", ""]
    for label, short, *_ in rows:
        lines.append(f"- **{label}** — {first_sentence(label)}.")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print("\n".join(lines[:6]))
    print(f"... {len(rows)} figures, {'all pass' if not problems else problems}")


if __name__ == "__main__":
    main()
