import ee; ee.Initialize(project='alpha-earth-app')
mb = ee.Image("projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_integration_v1")
b = mb.bandNames().getInfo(); print("MB bands:", b[:2], b[-3:], len(b))
era = ee.ImageCollection("ECMWF/ERA5_LAND/MONTHLY_AGGR").first()
eb = era.bandNames().getInfo()
print("ERA5 has t2m:", 'temperature_2m' in eb, "tp_sum:", 'total_precipitation_sum' in eb, "n=", len(eb))
dem = ee.ImageCollection("COPERNICUS/DEM/GLO30_2024_1")
print("DEM bands:", dem.first().bandNames().getInfo())
wc = ee.Image(ee.ImageCollection("ESA/WorldCover/v200").first()); print("WC:", wc.bandNames().getInfo())
ch = ee.Image("users/nlang/ETH_GlobalCanopyHeight_2020_10m_v1"); print("ETH CH:", ch.bandNames().getInfo())
